### ISSUE TITLE
hab_id.tif not reading in ArcGIS on Bren GIS machine

### ISSUE THREAD

**Issue by bbest** [marinebon/connectivity#1]
Hi @stephgad,

You were having trouble reading in the `hab_id.tif` (generated by [mbon_habitat_prep.Rmd](https://github.com/marinebon/connectivity/blob/4d39a49464eddbd72daca28e8247492817188c05/mbon_habitat_prep.Rmd#raster-manipulation)) on the Bren GIS machine CONSTANCE. We discussed using these files as the water mask.

When I read in `hab_id.tif` on the ArcGIS 10.2.2 loaded on my virtual PC from Mac laptop, the raster does show (although stops responding after painting top half).

![image](https://user-images.githubusercontent.com/2837257/28083124-3d44d5bc-6629-11e7-9ffa-9e492d2ab712.png)

Then after I build pyramids it goes black:

![image](https://user-images.githubusercontent.com/2837257/28082793-51d28228-6628-11e7-9fd3-cb1da16f0bea.png)

I recommend trying these:

1. Remove `hab_id.ovr` pyramid file if present in Windows Explorer and avoid building pyramids.

1. Work on it locally in `C:\temp` or similar.

1. Crop to study area, eg Southwest / Southeast (projected to same Mollweide) very first thing, so working with more reasonable subset.

Hopefully then you can use an expression like `Con(IsNull("hab_id"), 1, 0)` to create a water mask (see [How To: Convert NoData values to other values for raster data](http://support.esri.com/en/technical-article/000010059)).

**Comment by bbest** [comment]
Hi again @stephgad,

One more recommendation:

4. You could also try exporting from R in other formats and see if they play nicer with ArcGIS. Here's a snippet of new code in [mbon_habitat_prep.Rmd](https://github.com/marinebon/connectivity/blob/4d39a49464eddbd72daca28e8247492817188c05/mbon_habitat_prep.Rmd#raster-manipulation):

```r
# try other formats for ArcGIS ----
r_m = raster(tif_all)
for (ext in c('grd','asc','sdat','rst','nc','tif','envi','bil','img')){ # ext='grd'
  out = sprintf('%s.%s', tools::file_path_sans_ext(tif_all), ext)
  writeRaster(r_m, out)
}
```

**Comment by stephgad** [comment]
Hi @bbest 

When testing the connectivity tools in MGET with the new rasters, I get this message :

ValueError: The raster or raster layer P:\habitats\southwest-9km_patchid.tif, specified for the patchIDsRaster parameter, is a 64-bit floating point raster or raster layer but this function requires a raster or raster layer with one of the following pixel types: 8-bit signed integer', '8-bit unsigned integer', '16-bit signed integer', '16-bit unsigned integer', '32-bit signed integer', '32-bit unsigned integer', '64-bit signed integer', '64-bit unsigned integer. Please provide a raster or raster layer with an allowed pixel type.

I've tried the tool "copy raster"and changed the pixel type to "64-bit", but still get the same error message. When converting to a "32-bit unsigned integer" it changes all the NA land values to zero for the Patch ID raster, which MGET also doesn't like. My next step was to try changing those zero values back to NA... unless this is a rabbit hole and you have any other recommendations? 

Thanks! 

![mget_error](https://user-images.githubusercontent.com/18455676/28187789-bc553cbe-67d4-11e7-959d-809639877178.JPG)

**Comment by bbest** [comment]
Hi @stephgad,

Ok, so you want an integer raster. You can use:

- [`Int()`](http://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/int.htm) in ArcGIS with Raster Calculator to convert, or way better use
- [`writeRaster()`](https://www.rdocumentation.org/packages/raster/versions/2.5-8/topics/writeRaster) and specify argument `datatype=`:
   
    - `'INT1U'` for waterMaskRaster
    - `'INT4S'` for patchIDsRaster
    - `'FLT4S'` for patchCoverRaster
    
    to satisfy inputs for [Create Larval Dispersal Simulation From ArcGIS Rasters](http://code.nicholas.duke.edu/projects/mget/export/HEAD/MGET/Trunk/PythonPackage/dist/TracOnlineDocumentation/Documentation/ArcGISReference/LarvalDispersal.CreateSimulationFromArcGISRasters.html?format=raw).

For more details, see [`?dataType`](https://www.rdocumentation.org/packages/raster/versions/2.5-8/topics/dataType):
    
  - The following datatypes are available:
    
    ![image](https://user-images.githubusercontent.com/2837257/28189867-e418ccc2-67dc-11e7-9171-c78b313a977f.png)
  
  - INT4U is available but they are best avoided as R does not support 32-bit unsigned integers.

**Comment by stephgad** [comment]
The pixel type still says "double precision" even after specifying` datatype=` in `writeRaster()` and won't make it past the first tool. 
I'll keep working on it - just wanted to send and update

**Comment by bbest** [comment]
Hi @stephgad,

Can you please git commit and push the code so I can see in this repo that you used in both R and Python. I am suspicious of paths not being correct.

Note that you don't have to rerun all the code to convert. You can simply do something like:

```r
# overwrite existing raster with explicit datatype
tif = 'P:/dir/patchid.tif'
raster(tif) %>%
  writeRaster(tif, dataType='INT4S', overwrite=T)
```

**Comment by stephgad** [comment]
Hi @bbest 

The updated watermask.Rmd is committed and pushed to git - that was the only script I was working on

**Comment by bbest** [comment]
So is writeRaster() not successfully changing the datatype? Can you look at it in R and properties in ArcGIS? Did you try the Int() in ArcGIS as a fallback?

What's the network file share path for P:\ and the other drive with files? Can you please request access for me (bbest) -- maybe you already did and I forgot. Feel free to drop problematic files into our Google drive so I can debug.

**Comment by stephgad** [comment]
Hi @bbest 
 
writeRaster() is not successfully changing the datatype - still says double precision in properties in ArcGIS and "FLT4S" when checking the dataType in R

I tried the Int() in ArcGIS and it does converts the rasters to single integer - trying to run them in the MGET_test now, but it's taking way longer than a test usually does.

the network file share path for P:\ is  \\hyperv3\sgad-summer2017 - you should have access already, but let me know if you're having trouble with it, I'll send another email! 
and for H:\ it is \\babylon\co2017\sgad - you don't have access to this drive, but I'll send an email requesting it now!

**Comment by stephgad** [comment]
I also noticed the tool [help](http://code.nicholas.duke.edu/projects/mget/export/HEAD/MGET/Trunk/PythonPackage/dist/TracOnlineDocumentation/Documentation/ArcGISReference/LarvalDispersal.CreateSimulationFromArcGISRasters.html?format=raw) says "Patch IDs may range from 1 to 65,535, inclusive" and since our southwest-9km_patchid.tif ranges from 527 - 83,803 and southeast-9km_patchid.tif from 4,920 - 143,174 (both clearly over 65,535) I made new rasters with a 12km cell size insteand of 9km. Converted the new 12km rasters with int() and tried running in MGET but still came up with the same problem - continued running for a very long time without completing. 
I think we might want to consider making the study region smaller.

**Comment by stephgad** [comment]
Hi @bbest 

Good news is the first tool finished running over the weekend - the not so good news is it took hours when it should have taken minutes to finish. Also the third tool failed with a memory error
![out_of_mem](https://user-images.githubusercontent.com/18455676/28279110-4cac0106-6ad4-11e7-87f3-af793eba1ee9.JPG)

I'm going to make a new batch of rasters with a smaller buffer/study region, maybe 700km then 500km and test them in MGET

**Comment by bbest** [comment]
Hi @stephgad,

OK, that's good progress. I figured out how to at least create integer rasters from R using [`raster::as.logical()`](https://www.rdocumentation.org/packages/raster/versions/2.5-8/topics/as.logical) and `raster::as.integer()` instead of `raster::writeRaster()`...

```r
library(tidyverse)
library(sf)
library(raster)
library(mapview)  
library(mapedit)  

# read in original global raster in Mollweide
tif = '/Users/bbest/github/connectivity/data/hab_id.tif'
r = raster(tif_in)

# draw bbox of CA and get coords in Mollweide
m = editMap() # draw bbox
m_mol = m %>%
  st_transform(crs(r, asText=T))
bb = st_bbox(m_mol)

# crop to CA for easier testing
r_c = r %>%
  crop(extent(bb[c('xmin','xmax','ymin','ymax')]))

# writeRaster not working: always 64 Bit double precision in ArcGIS
writeRaster(
  r_c, '/Users/bbest/github/connectivity/data/habid.tif', overwrite=T)
writeRaster(
  r_c, '/Users/bbest/github/connectivity/data/habid_writeRaster-INT4S-bad.tif', 
  dataType='INT4S', overwrite=T)
writeRaster(
  !is.na(r_c), '/Users/bbest/github/connectivity/data/habid_writeRaster-INT1U-bad.tif', 
  dataType='INT4S', overwrite=T)
```

![image](https://user-images.githubusercontent.com/2837257/28284062-a3df6728-6ae4-11e7-8105-eecd8a0f45a3.png)


```r
# big integer: 32 Bit signed integer in ArcGIS
as.integer(
  r_c, 
  filename='/Users/bbest/github/connectivity/data/habid_as.integer.tif', 
  overwrite=T)
```

![image](https://user-images.githubusercontent.com/2837257/28283947-5b6f7762-6ae4-11e7-9587-8565a09ed505.png)

```r
# small integer: 16 Bit signed integer in ArcGIS
as.logical(
  !is.na(r_c), 
  filename='/Users/bbest/github/connectivity/data/habid_as.logical.tif', 
  overwrite=T)
```

![image](https://user-images.githubusercontent.com/2837257/28283997-79b7bc98-6ae4-11e7-8b67-50d1a85c14f2.png)

**Comment by stephgad** [comment]
Hi @bbest 

quick update: 

the southwest and southeast rasters with a 100km cell size ran through the MGET test!! 
![connectivity](https://user-images.githubusercontent.com/18455676/28392417-b4828660-6c96-11e7-850c-3c51881306ec.JPG)

I've been running the test model (1 day PLD) on the southeast 9km rasters since 11:00am this morning. It's still running, will update once it finishes.

**Comment by stephgad** [comment]
Hi @bbest 

The SW and SE 9km rasters exceed the the 65,535 cell limit and fail on the third tool (Run Larval Dispersal Simulation) with a memory error 
![runtime error](https://user-images.githubusercontent.com/18455676/28429507-d1084bf8-6d31-11e7-8e13-58e88b0c70a3.JPG)


The problem with decreasing the study region from 1,000km to 700km (still with a 9km cell size) is that the southeast raster is still too large with 85,446 cells. When reducing the region buffer to 600km, the three southeast sanctuaries no longer overlap. I can increase the cell size, but that will impact the currents data. 

Are you around MSI today? Would you have time for a quick meeting? If not, do you have any suggestions on how to move forward? Good news is once the cell number issue is resolved, I think the rasters will be ready to start doing model runs on!

**Comment by bbest** [comment]
Hi Stephanie,

Ok, getting close! Seems like we should aggregate to something larger than
9km. I am curious if the size limit is based on the entire size of raster
(cells = rows * cols) or the number of non-NA cells (ie water mask), which
makes more sense.

I'll be on campus this afternoon, available to meet anytime 2-5pm. Will
look for you in GIS lab at 2.

**Comment by stephgad** [comment]
Closing this issue b/c past original problem by using `ocean_mask.tif` with `prep_rasters.R`.

- @bbest
